site_name: SignLink-ISL

theme:
  name: material
  # logo: img/favicon.ico
  favicon: img/favicon.ico
  icon:
    repo: fontawesome/brands/github
  palette:
    # Light mode
    - scheme: default
      primary: teal
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    # Dark mode
    - scheme: slate
      primary: deep orange
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.path
    - content.code.copy       # Enables the copy button for code snippets
    - search.suggest          # Search suggestions
    - search.highlight        # Highlights search results
    # - navigation.tabs         # Tabbed navigation for better organization
    - accessibility           # Adds font resizing controls for accessibility
    - toc.integrate
    - navigation.top
    - content.code.select
    - content.code.annotate

markdown_extensions:
  - pymdownx.highlight:
      linenums: true          # Enable line numbers
  - pymdownx.superfences       # Enhanced code block support
  - codehilite:
      guess_lang: false       # Avoid language guessing
      linenums: true
  - toc:                      # Adds table of contents to pages
      permalink: true

nav:
  - Home: index.md

  - Setup: setup.md

  - Dataset: dataset.md

  - Data_Loader:
      - Video Dataset Loader MediaPipe Interpolated CV: data_loader/video_dataset_loader_mediapipe_interpolated_cv.md
      - Video Dataset Loader MediaPipe Keypoints: data_loader/Video_dataset_loader_mediapipe_keypoints.md
      - Video Dataset Loader MediaPipe: data_loader/Video_dataset_loader_mediapipe.md
      - Video Dataset Loader: data_loader/VideoDatasetLoader.md

  - Trainers:
    - About: trainers/index.md
    - Trainer:
        - __init__: trainers/trainer/init.md
        - train_step: trainers/trainer/train_step.md
        - test_step: trainers/trainer/test_step.md
    - Trainer_Batch_Slice: 
        - __init__: trainers/trainer_batch_slice/init.md
        - train_step_pickle_slice_batch: trainers/trainer_batch_slice/train_step_pickle_slice_batch.md
        - test_step_pickle_slice_batch: trainers/trainer_batch_slice/test_step_pickle_slice_batch.md
        - Sliceoutofbounds: trainers/trainer_batch_slice/Sliceoutofbounds.md
    - Trainer_Pickle_Preload:
        - __init__: trainers/trainer_pickle_preload/init.md
        - train_step_pickle: trainers/trainer_pickle_preload/train_step_pickle.md
        - test_step_pickle: trainers/trainer_pickle_preload/test_step_pickle.md
    - Trainer_Pickle:
        - __init__: trainers/trainer_pickle/init.md
        - train_step_pickle: trainers/trainer_pickle/train_step_pickle.md
        - test_step_pickle: trainers/trainer_pickle/test_step_pickle.md
  
  - Utils:
    - About: utils/index.md
    - Data_words:
        - data_and_words: utils/data_words/data_and_words.md
        - random_split: utils/data_words/random_split.md
    - Metrics:
        - display_confusion: utils/metrics/display_conf_matrix.md
        - show_performance: utils/metrics/show_performance_scores.md
    - Pickle:
        - get_all_files: utils/pickle/get_all_file_paths.md
        - pickle_data: utils/pickle/pickle_data.md
        - preload_tensors: utils/pickle/preload_tensors.md
    - Preload:
        - preload_data: utils/preload/preload_data.md
    - Save Load:
        - load_checkpoint: utils/save_load/load_checkpoint.md
        - load_model: utils/save_load/load_model.md
        - save_checkpoint: utils/save_load/save_checkpoint.md
    - Show Sequence:
        - show_sequence: utils/show_sequence/show_sequence.md
  
  - Training: training.md
repo_url: https://github.com/Naneet/SignLink-ISL
repo_name: Naneet/SignLink-ISL
use_directory_urls: true
plugins:
  - git-committers:
      repository: https://github.com/Naneet/SignLink-ISL
      branch: main
  - search
  - offline
  - redirects:              
      404.md: 404.md
extra_javascript:
  - js/clipboard.min.js
  - js/config.js
  
