- name: Deploy to GitHub Pages
  uses: peaceiris/actions-gh-pages@v3
  with:
    github_token: ${{ secrets.GH_TOKEN }}
    publish_dir: ./site  # Replace with your folder
    publish_branch: gh-pages
